Updated secret script

diff --git a/devcli/devcli.d/secret b/devcli/devcli.d/secret
--- a/devcli/devcli.d/secret
+++ b/devcli/devcli.d/secret
@@ -1,39 +1,23 @@
 #!/bin/bash
 
-SUBCOMMAND_DESC="Scan for secret leaks"
-SUBCOMMAND_HELP=$(
-  cat <<EOH
+read -r -d '' __helptext <<-'EOF' || true                      # exits non-zero when EOF encountered
+ Scan for secret leaks.
+EOF
 
-check -s <pattern_file>  <list_of_files_to_search>                   Check for secret leaks
+[[ "${__usage+x}" ]] || read -r -d '' __usage <<-'EOF' || true # exits non-zero when EOF encountered
+  -s --secret-pattern-file  [arg] Comma-separated list of files containing secret string patterns. Required.
+  -r --repo-path            [arg] Path to Git repo to inspect. Required.
+EOF
 
-EOH
-)
+source $ROOT_DIR/_boilerplate.sh
 
-case ${1} in
-check)
-
-  shift #Remove the subcommand from $@
-
-  while getopts ":s:" OPTION; do
-    case $OPTION in
-    s) patterns=$OPTARG ;;
-    *)
-      echo $SUBCOMMAND_HELP
-      ;;
-    esac
-  done
-
-  shift $((OPTIND - 1))
-
-  for i in $(echo $patterns | sed "s/,/ /g"); do
-    # call your procedure/other scripts here below
-    grep -iEn -f $i $@
-    status=$?
-    if $(exit $status); then
-      exit 1
-    fi
-  done
-
-  ;;
-
-esac
+files=$(git diff --name-only --cached)
+for i in $(echo "${arg_s}" | sed "s/,/ /g"); do
+  # call your procedure/other scripts here below
+  set +o errexit
+  grep -iEn -f $i ${files[@]}
+  status=$?
+  if $(exit $status); then
+    exit 1
+  fi
+done
